# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protomagic < Formula
  desc "ProtoMagic is a CLI that helps convert database tables into Protocol Buffers files (.proto)."
  homepage "https://github.com/toolsascode/protomagic"
  version "0.1.0-beta"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/toolsascode/protomagic/releases/download/v0.1.0-beta/protomagic_Darwin_x86_64.tar.gz"
      sha256 "64759f3d06bbd99116eab65b1d3da3916f9566ce680d69f762b1b40781e0ccb7"

      def install
        bin.install "protomagic"
      end
    end
    on_arm do
      url "https://github.com/toolsascode/protomagic/releases/download/v0.1.0-beta/protomagic_Darwin_arm64.tar.gz"
      sha256 "cd0c48e2fac2ed2eddca4e73bf2da725bc9cd8760b941325ca6f58443ffbe9ed"

      def install
        bin.install "protomagic"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/protomagic/releases/download/v0.1.0-beta/protomagic_Linux_x86_64.tar.gz"
        sha256 "cf1024a2ad53d743469d45bd2c848a989495a8575aa4370c65d3212f06e2878b"

        def install
          bin.install "protomagic"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toolsascode/protomagic/releases/download/v0.1.0-beta/protomagic_Linux_arm64.tar.gz"
        sha256 "697aa2b00ed6cf722e2b1a609fce1bd090e4a33a6b04c3b3d536d40ad00906b3"

        def install
          bin.install "protomagic"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
