log:
  level: debug
databases:
  postgresql:
    dataSourceName: postgres://postgres:12345@localhost:5432/protomagic?sslmode=disable
  mysql:
    dataSourceName: root:12345@tcp(127.0.0.1:3306)/protomagic
protobuf:
  templateFile: null
  syntax: proto3
  apiVersion: v1
  output:
    reset: true
    path: ./proto
  customized:
    options:
      java: true
      objc: true
      csharp: true
      php: true
      ruby: true
    mapsTypes:
      # DB Type: Protobuf Type
      VARCHAR: string
      CHARACTER: string
      TIMESTAMP: google.protobuf.Timestamp
      DATE: google.protobuf.date
    fieldBehavior:
      # DB Column Name 1: "(google.api.field_behavior) = OUTPUT_ONLY"
      # DB Column Name 2: "(google.api.field_behavior) = OUTPUT_ONLY"
      # etc...
      feedback_at: "[(google.api.field_behavior) = OUTPUT_ONLY]"
      initialize_at: "[(google.api.field_behavior) = OUTPUT_ONLY, \n(google.api.field_behavior) = IMMUTABLE]"
