name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go get ./cmd/protomagic
      - name: Build
        run: go build -v ./cmd/protomagic
      - name: Test with the Go CLI
        run: go test ./cmd/protomagic